import { ConfigType } from 'src/app/shared/enums/config-type.enum';
import { ContactInfo } from './contact-info.model';
import { CustomFeatures } from './custom-features.model';
import { EmailOptions } from './email-options.model';
import { FopOptions } from './fop-options.model';
import { PnrOptions } from './pnr-options.model';
import { ClientInfo } from './client-info.model';
import { SiteOptions } from './site-options.model';
import { RedemptionConfig } from './redemption-config.model';
import { CreditCard } from './credit-card.model';
import { GhostCreditCard } from './ghost-credit-card.model';
import { GdsType } from 'src/app/shared/enums/gds-type.enum';
import { SearchFormConditions } from './search-form-conditions-model';
import { ItineraryRequirements } from './itinerary-requirements.model';
import { PageConfig } from './page-config.model';
import { Currency } from './currency.model';
import { SecondaryPhoneConfig } from './phone-model';

export class ProgramConfig {
  configType: ConfigType;
  customFeatures: CustomFeatures;
  emailOptions: EmailOptions;
  fopOptions: FopOptions;
  pnrOptions: PnrOptions;
  programID: string;
  programName: string;
  programPhone: string;
  clientInfo: ClientInfo;
  siteOptions: SiteOptions;
  redemptionConfig: RedemptionConfig;
  creditCard: CreditCard;
  ghostCreditCard: GhostCreditCard;
  gDS: GdsType;
  urlval: string;
  contactInfo: ContactInfo;
  searchFormConditions: SearchFormConditions;
  hardItineraryRequirements: ItineraryRequirements;
  softItineraryRequirements: ItineraryRequirements;
  pageConfigs: { [key: string]: PageConfig };
  miscDataLabels: string[];
  currency: Currency;
  secondaryPhoneConfig: SecondaryPhoneConfig;
  flightPricingMarkup: number;
  isEnabled: boolean;
  headerImage: string;
  styleSheet: string;
  confNumLabel: string;
  backgroundColor: string;
  isDemoMeeting: boolean;
}
